[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt && gunicorn -b 0.0.0.0:$PORT routes:app"
  publish = "app"

[context.production.environment]
  PYTHON_VERSION = "3.8"
