[build]
  command = "pip install -r requirements.txt"
  publish = "app/templates"  # Adjust based on your project structure

[context.production.environment]
  PYTHON_VERSION = "3.8"  # Specify the Python version you are using

[context.split1]
  command = "echo This is a different build context"
